/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PedidosLojinhaRouteImport } from './routes/pedidos-lojinha'
import { Route as MycardRouteImport } from './routes/mycard'
import { Route as LojinhaRouteImport } from './routes/lojinha'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LanchoneteRouteImport } from './routes/lanchonete'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CardsIndexRouteImport } from './routes/cards/index'
import { Route as VendasLojinhaRouteImport } from './routes/vendas/lojinha'
import { Route as VendasLanchoneteRouteImport } from './routes/vendas/lanchonete'
import { Route as HistoricoLojinhaRouteImport } from './routes/historico/lojinha'
import { Route as HistoricoLanchoneteRouteImport } from './routes/historico/lanchonete'
import { Route as CardsDebitRouteImport } from './routes/cards/debit'
import { Route as CardsCreateRouteImport } from './routes/cards/create'
import { Route as CardsBalanceRouteImport } from './routes/cards/balance'
import { Route as CardsAssociateRouteImport } from './routes/cards/associate'
import { Route as CardsAddRouteImport } from './routes/cards/add'

const PedidosLojinhaRoute = PedidosLojinhaRouteImport.update({
  id: '/pedidos-lojinha',
  path: '/pedidos-lojinha',
  getParentRoute: () => rootRouteImport,
} as any)
const MycardRoute = MycardRouteImport.update({
  id: '/mycard',
  path: '/mycard',
  getParentRoute: () => rootRouteImport,
} as any)
const LojinhaRoute = LojinhaRouteImport.update({
  id: '/lojinha',
  path: '/lojinha',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LanchoneteRoute = LanchoneteRouteImport.update({
  id: '/lanchonete',
  path: '/lanchonete',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CardsIndexRoute = CardsIndexRouteImport.update({
  id: '/cards/',
  path: '/cards/',
  getParentRoute: () => rootRouteImport,
} as any)
const VendasLojinhaRoute = VendasLojinhaRouteImport.update({
  id: '/vendas/lojinha',
  path: '/vendas/lojinha',
  getParentRoute: () => rootRouteImport,
} as any)
const VendasLanchoneteRoute = VendasLanchoneteRouteImport.update({
  id: '/vendas/lanchonete',
  path: '/vendas/lanchonete',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoricoLojinhaRoute = HistoricoLojinhaRouteImport.update({
  id: '/historico/lojinha',
  path: '/historico/lojinha',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoricoLanchoneteRoute = HistoricoLanchoneteRouteImport.update({
  id: '/historico/lanchonete',
  path: '/historico/lanchonete',
  getParentRoute: () => rootRouteImport,
} as any)
const CardsDebitRoute = CardsDebitRouteImport.update({
  id: '/cards/debit',
  path: '/cards/debit',
  getParentRoute: () => rootRouteImport,
} as any)
const CardsCreateRoute = CardsCreateRouteImport.update({
  id: '/cards/create',
  path: '/cards/create',
  getParentRoute: () => rootRouteImport,
} as any)
const CardsBalanceRoute = CardsBalanceRouteImport.update({
  id: '/cards/balance',
  path: '/cards/balance',
  getParentRoute: () => rootRouteImport,
} as any)
const CardsAssociateRoute = CardsAssociateRouteImport.update({
  id: '/cards/associate',
  path: '/cards/associate',
  getParentRoute: () => rootRouteImport,
} as any)
const CardsAddRoute = CardsAddRouteImport.update({
  id: '/cards/add',
  path: '/cards/add',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/lanchonete': typeof LanchoneteRoute
  '/login': typeof LoginRoute
  '/lojinha': typeof LojinhaRoute
  '/mycard': typeof MycardRoute
  '/pedidos-lojinha': typeof PedidosLojinhaRoute
  '/cards/add': typeof CardsAddRoute
  '/cards/associate': typeof CardsAssociateRoute
  '/cards/balance': typeof CardsBalanceRoute
  '/cards/create': typeof CardsCreateRoute
  '/cards/debit': typeof CardsDebitRoute
  '/historico/lanchonete': typeof HistoricoLanchoneteRoute
  '/historico/lojinha': typeof HistoricoLojinhaRoute
  '/vendas/lanchonete': typeof VendasLanchoneteRoute
  '/vendas/lojinha': typeof VendasLojinhaRoute
  '/cards': typeof CardsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/lanchonete': typeof LanchoneteRoute
  '/login': typeof LoginRoute
  '/lojinha': typeof LojinhaRoute
  '/mycard': typeof MycardRoute
  '/pedidos-lojinha': typeof PedidosLojinhaRoute
  '/cards/add': typeof CardsAddRoute
  '/cards/associate': typeof CardsAssociateRoute
  '/cards/balance': typeof CardsBalanceRoute
  '/cards/create': typeof CardsCreateRoute
  '/cards/debit': typeof CardsDebitRoute
  '/historico/lanchonete': typeof HistoricoLanchoneteRoute
  '/historico/lojinha': typeof HistoricoLojinhaRoute
  '/vendas/lanchonete': typeof VendasLanchoneteRoute
  '/vendas/lojinha': typeof VendasLojinhaRoute
  '/cards': typeof CardsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_layout': typeof LayoutRoute
  '/admin': typeof AdminRoute
  '/lanchonete': typeof LanchoneteRoute
  '/login': typeof LoginRoute
  '/lojinha': typeof LojinhaRoute
  '/mycard': typeof MycardRoute
  '/pedidos-lojinha': typeof PedidosLojinhaRoute
  '/cards/add': typeof CardsAddRoute
  '/cards/associate': typeof CardsAssociateRoute
  '/cards/balance': typeof CardsBalanceRoute
  '/cards/create': typeof CardsCreateRoute
  '/cards/debit': typeof CardsDebitRoute
  '/historico/lanchonete': typeof HistoricoLanchoneteRoute
  '/historico/lojinha': typeof HistoricoLojinhaRoute
  '/vendas/lanchonete': typeof VendasLanchoneteRoute
  '/vendas/lojinha': typeof VendasLojinhaRoute
  '/cards/': typeof CardsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/lanchonete'
    | '/login'
    | '/lojinha'
    | '/mycard'
    | '/pedidos-lojinha'
    | '/cards/add'
    | '/cards/associate'
    | '/cards/balance'
    | '/cards/create'
    | '/cards/debit'
    | '/historico/lanchonete'
    | '/historico/lojinha'
    | '/vendas/lanchonete'
    | '/vendas/lojinha'
    | '/cards'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/lanchonete'
    | '/login'
    | '/lojinha'
    | '/mycard'
    | '/pedidos-lojinha'
    | '/cards/add'
    | '/cards/associate'
    | '/cards/balance'
    | '/cards/create'
    | '/cards/debit'
    | '/historico/lanchonete'
    | '/historico/lojinha'
    | '/vendas/lanchonete'
    | '/vendas/lojinha'
    | '/cards'
  id:
    | '__root__'
    | '/'
    | '/_layout'
    | '/admin'
    | '/lanchonete'
    | '/login'
    | '/lojinha'
    | '/mycard'
    | '/pedidos-lojinha'
    | '/cards/add'
    | '/cards/associate'
    | '/cards/balance'
    | '/cards/create'
    | '/cards/debit'
    | '/historico/lanchonete'
    | '/historico/lojinha'
    | '/vendas/lanchonete'
    | '/vendas/lojinha'
    | '/cards/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LayoutRoute: typeof LayoutRoute
  AdminRoute: typeof AdminRoute
  LanchoneteRoute: typeof LanchoneteRoute
  LoginRoute: typeof LoginRoute
  LojinhaRoute: typeof LojinhaRoute
  MycardRoute: typeof MycardRoute
  PedidosLojinhaRoute: typeof PedidosLojinhaRoute
  CardsAddRoute: typeof CardsAddRoute
  CardsAssociateRoute: typeof CardsAssociateRoute
  CardsBalanceRoute: typeof CardsBalanceRoute
  CardsCreateRoute: typeof CardsCreateRoute
  CardsDebitRoute: typeof CardsDebitRoute
  HistoricoLanchoneteRoute: typeof HistoricoLanchoneteRoute
  HistoricoLojinhaRoute: typeof HistoricoLojinhaRoute
  VendasLanchoneteRoute: typeof VendasLanchoneteRoute
  VendasLojinhaRoute: typeof VendasLojinhaRoute
  CardsIndexRoute: typeof CardsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pedidos-lojinha': {
      id: '/pedidos-lojinha'
      path: '/pedidos-lojinha'
      fullPath: '/pedidos-lojinha'
      preLoaderRoute: typeof PedidosLojinhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mycard': {
      id: '/mycard'
      path: '/mycard'
      fullPath: '/mycard'
      preLoaderRoute: typeof MycardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lojinha': {
      id: '/lojinha'
      path: '/lojinha'
      fullPath: '/lojinha'
      preLoaderRoute: typeof LojinhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lanchonete': {
      id: '/lanchonete'
      path: '/lanchonete'
      fullPath: '/lanchonete'
      preLoaderRoute: typeof LanchoneteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cards/': {
      id: '/cards/'
      path: '/cards'
      fullPath: '/cards'
      preLoaderRoute: typeof CardsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendas/lojinha': {
      id: '/vendas/lojinha'
      path: '/vendas/lojinha'
      fullPath: '/vendas/lojinha'
      preLoaderRoute: typeof VendasLojinhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendas/lanchonete': {
      id: '/vendas/lanchonete'
      path: '/vendas/lanchonete'
      fullPath: '/vendas/lanchonete'
      preLoaderRoute: typeof VendasLanchoneteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historico/lojinha': {
      id: '/historico/lojinha'
      path: '/historico/lojinha'
      fullPath: '/historico/lojinha'
      preLoaderRoute: typeof HistoricoLojinhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historico/lanchonete': {
      id: '/historico/lanchonete'
      path: '/historico/lanchonete'
      fullPath: '/historico/lanchonete'
      preLoaderRoute: typeof HistoricoLanchoneteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cards/debit': {
      id: '/cards/debit'
      path: '/cards/debit'
      fullPath: '/cards/debit'
      preLoaderRoute: typeof CardsDebitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cards/create': {
      id: '/cards/create'
      path: '/cards/create'
      fullPath: '/cards/create'
      preLoaderRoute: typeof CardsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cards/balance': {
      id: '/cards/balance'
      path: '/cards/balance'
      fullPath: '/cards/balance'
      preLoaderRoute: typeof CardsBalanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cards/associate': {
      id: '/cards/associate'
      path: '/cards/associate'
      fullPath: '/cards/associate'
      preLoaderRoute: typeof CardsAssociateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cards/add': {
      id: '/cards/add'
      path: '/cards/add'
      fullPath: '/cards/add'
      preLoaderRoute: typeof CardsAddRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LayoutRoute: LayoutRoute,
  AdminRoute: AdminRoute,
  LanchoneteRoute: LanchoneteRoute,
  LoginRoute: LoginRoute,
  LojinhaRoute: LojinhaRoute,
  MycardRoute: MycardRoute,
  PedidosLojinhaRoute: PedidosLojinhaRoute,
  CardsAddRoute: CardsAddRoute,
  CardsAssociateRoute: CardsAssociateRoute,
  CardsBalanceRoute: CardsBalanceRoute,
  CardsCreateRoute: CardsCreateRoute,
  CardsDebitRoute: CardsDebitRoute,
  HistoricoLanchoneteRoute: HistoricoLanchoneteRoute,
  HistoricoLojinhaRoute: HistoricoLojinhaRoute,
  VendasLanchoneteRoute: VendasLanchoneteRoute,
  VendasLojinhaRoute: VendasLojinhaRoute,
  CardsIndexRoute: CardsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
