/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutPedidosSapatinhoVelozRouteImport } from './routes/_layout/pedidos-sapatinho-veloz'
import { Route as LayoutPedidosLojinhaRouteImport } from './routes/_layout/pedidos-lojinha'
import { Route as LayoutMycardRouteImport } from './routes/_layout/mycard'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'
import { Route as LayoutSapatinhoVelozIndexRouteImport } from './routes/_layout/sapatinho-veloz/index'
import { Route as LayoutLojinhaIndexRouteImport } from './routes/_layout/lojinha/index'
import { Route as LayoutLanchoneteIndexRouteImport } from './routes/_layout/lanchonete/index'
import { Route as LayoutCardsIndexRouteImport } from './routes/_layout/cards/index'
import { Route as LayoutVendasLojinhaRouteImport } from './routes/_layout/vendas/lojinha'
import { Route as LayoutVendasLanchoneteRouteImport } from './routes/_layout/vendas/lanchonete'
import { Route as LayoutSapatinhoVelozSelectRouteImport } from './routes/_layout/sapatinho-veloz/select'
import { Route as LayoutSapatinhoVelozSalesRouteImport } from './routes/_layout/sapatinho-veloz/sales'
import { Route as LayoutLojinhaSelectRouteImport } from './routes/_layout/lojinha/select'
import { Route as LayoutLanchoneteSelectRouteImport } from './routes/_layout/lanchonete/select'
import { Route as LayoutHistoricoSapatinhoRouteImport } from './routes/_layout/historico/sapatinho'
import { Route as LayoutHistoricoLojinhaRouteImport } from './routes/_layout/historico/lojinha'
import { Route as LayoutHistoricoLanchoneteRouteImport } from './routes/_layout/historico/lanchonete'
import { Route as LayoutCardsDebitRouteImport } from './routes/_layout/cards/debit'
import { Route as LayoutCardsCreateRouteImport } from './routes/_layout/cards/create'
import { Route as LayoutCardsBalanceRouteImport } from './routes/_layout/cards/balance'
import { Route as LayoutCardsAssociateRouteImport } from './routes/_layout/cards/associate'
import { Route as LayoutCardsAddRouteImport } from './routes/_layout/cards/add'
import { Route as LayoutSapatinhoVelozProductsIndexRouteImport } from './routes/_layout/sapatinho-veloz/products/index'
import { Route as LayoutLojinhaProductsIndexRouteImport } from './routes/_layout/lojinha/products/index'
import { Route as LayoutLanchoneteProductsIndexRouteImport } from './routes/_layout/lanchonete/products/index'
import { Route as LayoutSapatinhoVelozProductsCreateRouteImport } from './routes/_layout/sapatinho-veloz/products/create'
import { Route as LayoutLojinhaProductsCreateRouteImport } from './routes/_layout/lojinha/products/create'
import { Route as LayoutLanchoneteProductsCreateRouteImport } from './routes/_layout/lanchonete/products/create'
import { Route as LayoutSapatinhoVelozProductsIdEditRouteImport } from './routes/_layout/sapatinho-veloz/products/$id/edit'
import { Route as LayoutLojinhaProductsIdEditRouteImport } from './routes/_layout/lojinha/products/$id/edit'
import { Route as LayoutLanchoneteProductsIdEditRouteImport } from './routes/_layout/lanchonete/products/$id/edit'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPedidosSapatinhoVelozRoute =
  LayoutPedidosSapatinhoVelozRouteImport.update({
    id: '/pedidos-sapatinho-veloz',
    path: '/pedidos-sapatinho-veloz',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutPedidosLojinhaRoute = LayoutPedidosLojinhaRouteImport.update({
  id: '/pedidos-lojinha',
  path: '/pedidos-lojinha',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutMycardRoute = LayoutMycardRouteImport.update({
  id: '/mycard',
  path: '/mycard',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSapatinhoVelozIndexRoute =
  LayoutSapatinhoVelozIndexRouteImport.update({
    id: '/sapatinho-veloz/',
    path: '/sapatinho-veloz/',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutLojinhaIndexRoute = LayoutLojinhaIndexRouteImport.update({
  id: '/lojinha/',
  path: '/lojinha/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutLanchoneteIndexRoute = LayoutLanchoneteIndexRouteImport.update({
  id: '/lanchonete/',
  path: '/lanchonete/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCardsIndexRoute = LayoutCardsIndexRouteImport.update({
  id: '/cards/',
  path: '/cards/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutVendasLojinhaRoute = LayoutVendasLojinhaRouteImport.update({
  id: '/vendas/lojinha',
  path: '/vendas/lojinha',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutVendasLanchoneteRoute = LayoutVendasLanchoneteRouteImport.update({
  id: '/vendas/lanchonete',
  path: '/vendas/lanchonete',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSapatinhoVelozSelectRoute =
  LayoutSapatinhoVelozSelectRouteImport.update({
    id: '/sapatinho-veloz/select',
    path: '/sapatinho-veloz/select',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutSapatinhoVelozSalesRoute =
  LayoutSapatinhoVelozSalesRouteImport.update({
    id: '/sapatinho-veloz/sales',
    path: '/sapatinho-veloz/sales',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutLojinhaSelectRoute = LayoutLojinhaSelectRouteImport.update({
  id: '/lojinha/select',
  path: '/lojinha/select',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutLanchoneteSelectRoute = LayoutLanchoneteSelectRouteImport.update({
  id: '/lanchonete/select',
  path: '/lanchonete/select',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutHistoricoSapatinhoRoute =
  LayoutHistoricoSapatinhoRouteImport.update({
    id: '/historico/sapatinho',
    path: '/historico/sapatinho',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutHistoricoLojinhaRoute = LayoutHistoricoLojinhaRouteImport.update({
  id: '/historico/lojinha',
  path: '/historico/lojinha',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutHistoricoLanchoneteRoute =
  LayoutHistoricoLanchoneteRouteImport.update({
    id: '/historico/lanchonete',
    path: '/historico/lanchonete',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutCardsDebitRoute = LayoutCardsDebitRouteImport.update({
  id: '/cards/debit',
  path: '/cards/debit',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCardsCreateRoute = LayoutCardsCreateRouteImport.update({
  id: '/cards/create',
  path: '/cards/create',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCardsBalanceRoute = LayoutCardsBalanceRouteImport.update({
  id: '/cards/balance',
  path: '/cards/balance',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCardsAssociateRoute = LayoutCardsAssociateRouteImport.update({
  id: '/cards/associate',
  path: '/cards/associate',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCardsAddRoute = LayoutCardsAddRouteImport.update({
  id: '/cards/add',
  path: '/cards/add',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSapatinhoVelozProductsIndexRoute =
  LayoutSapatinhoVelozProductsIndexRouteImport.update({
    id: '/sapatinho-veloz/products/',
    path: '/sapatinho-veloz/products/',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutLojinhaProductsIndexRoute =
  LayoutLojinhaProductsIndexRouteImport.update({
    id: '/lojinha/products/',
    path: '/lojinha/products/',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutLanchoneteProductsIndexRoute =
  LayoutLanchoneteProductsIndexRouteImport.update({
    id: '/lanchonete/products/',
    path: '/lanchonete/products/',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutSapatinhoVelozProductsCreateRoute =
  LayoutSapatinhoVelozProductsCreateRouteImport.update({
    id: '/sapatinho-veloz/products/create',
    path: '/sapatinho-veloz/products/create',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutLojinhaProductsCreateRoute =
  LayoutLojinhaProductsCreateRouteImport.update({
    id: '/lojinha/products/create',
    path: '/lojinha/products/create',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutLanchoneteProductsCreateRoute =
  LayoutLanchoneteProductsCreateRouteImport.update({
    id: '/lanchonete/products/create',
    path: '/lanchonete/products/create',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutSapatinhoVelozProductsIdEditRoute =
  LayoutSapatinhoVelozProductsIdEditRouteImport.update({
    id: '/sapatinho-veloz/products/$id/edit',
    path: '/sapatinho-veloz/products/$id/edit',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutLojinhaProductsIdEditRoute =
  LayoutLojinhaProductsIdEditRouteImport.update({
    id: '/lojinha/products/$id/edit',
    path: '/lojinha/products/$id/edit',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutLanchoneteProductsIdEditRoute =
  LayoutLanchoneteProductsIdEditRouteImport.update({
    id: '/lanchonete/products/$id/edit',
    path: '/lanchonete/products/$id/edit',
    getParentRoute: () => LayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/admin': typeof LayoutAdminRoute
  '/mycard': typeof LayoutMycardRoute
  '/pedidos-lojinha': typeof LayoutPedidosLojinhaRoute
  '/pedidos-sapatinho-veloz': typeof LayoutPedidosSapatinhoVelozRoute
  '/': typeof LayoutIndexRoute
  '/cards/add': typeof LayoutCardsAddRoute
  '/cards/associate': typeof LayoutCardsAssociateRoute
  '/cards/balance': typeof LayoutCardsBalanceRoute
  '/cards/create': typeof LayoutCardsCreateRoute
  '/cards/debit': typeof LayoutCardsDebitRoute
  '/historico/lanchonete': typeof LayoutHistoricoLanchoneteRoute
  '/historico/lojinha': typeof LayoutHistoricoLojinhaRoute
  '/historico/sapatinho': typeof LayoutHistoricoSapatinhoRoute
  '/lanchonete/select': typeof LayoutLanchoneteSelectRoute
  '/lojinha/select': typeof LayoutLojinhaSelectRoute
  '/sapatinho-veloz/sales': typeof LayoutSapatinhoVelozSalesRoute
  '/sapatinho-veloz/select': typeof LayoutSapatinhoVelozSelectRoute
  '/vendas/lanchonete': typeof LayoutVendasLanchoneteRoute
  '/vendas/lojinha': typeof LayoutVendasLojinhaRoute
  '/cards': typeof LayoutCardsIndexRoute
  '/lanchonete': typeof LayoutLanchoneteIndexRoute
  '/lojinha': typeof LayoutLojinhaIndexRoute
  '/sapatinho-veloz': typeof LayoutSapatinhoVelozIndexRoute
  '/lanchonete/products/create': typeof LayoutLanchoneteProductsCreateRoute
  '/lojinha/products/create': typeof LayoutLojinhaProductsCreateRoute
  '/sapatinho-veloz/products/create': typeof LayoutSapatinhoVelozProductsCreateRoute
  '/lanchonete/products': typeof LayoutLanchoneteProductsIndexRoute
  '/lojinha/products': typeof LayoutLojinhaProductsIndexRoute
  '/sapatinho-veloz/products': typeof LayoutSapatinhoVelozProductsIndexRoute
  '/lanchonete/products/$id/edit': typeof LayoutLanchoneteProductsIdEditRoute
  '/lojinha/products/$id/edit': typeof LayoutLojinhaProductsIdEditRoute
  '/sapatinho-veloz/products/$id/edit': typeof LayoutSapatinhoVelozProductsIdEditRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/admin': typeof LayoutAdminRoute
  '/mycard': typeof LayoutMycardRoute
  '/pedidos-lojinha': typeof LayoutPedidosLojinhaRoute
  '/pedidos-sapatinho-veloz': typeof LayoutPedidosSapatinhoVelozRoute
  '/': typeof LayoutIndexRoute
  '/cards/add': typeof LayoutCardsAddRoute
  '/cards/associate': typeof LayoutCardsAssociateRoute
  '/cards/balance': typeof LayoutCardsBalanceRoute
  '/cards/create': typeof LayoutCardsCreateRoute
  '/cards/debit': typeof LayoutCardsDebitRoute
  '/historico/lanchonete': typeof LayoutHistoricoLanchoneteRoute
  '/historico/lojinha': typeof LayoutHistoricoLojinhaRoute
  '/historico/sapatinho': typeof LayoutHistoricoSapatinhoRoute
  '/lanchonete/select': typeof LayoutLanchoneteSelectRoute
  '/lojinha/select': typeof LayoutLojinhaSelectRoute
  '/sapatinho-veloz/sales': typeof LayoutSapatinhoVelozSalesRoute
  '/sapatinho-veloz/select': typeof LayoutSapatinhoVelozSelectRoute
  '/vendas/lanchonete': typeof LayoutVendasLanchoneteRoute
  '/vendas/lojinha': typeof LayoutVendasLojinhaRoute
  '/cards': typeof LayoutCardsIndexRoute
  '/lanchonete': typeof LayoutLanchoneteIndexRoute
  '/lojinha': typeof LayoutLojinhaIndexRoute
  '/sapatinho-veloz': typeof LayoutSapatinhoVelozIndexRoute
  '/lanchonete/products/create': typeof LayoutLanchoneteProductsCreateRoute
  '/lojinha/products/create': typeof LayoutLojinhaProductsCreateRoute
  '/sapatinho-veloz/products/create': typeof LayoutSapatinhoVelozProductsCreateRoute
  '/lanchonete/products': typeof LayoutLanchoneteProductsIndexRoute
  '/lojinha/products': typeof LayoutLojinhaProductsIndexRoute
  '/sapatinho-veloz/products': typeof LayoutSapatinhoVelozProductsIndexRoute
  '/lanchonete/products/$id/edit': typeof LayoutLanchoneteProductsIdEditRoute
  '/lojinha/products/$id/edit': typeof LayoutLojinhaProductsIdEditRoute
  '/sapatinho-veloz/products/$id/edit': typeof LayoutSapatinhoVelozProductsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/mycard': typeof LayoutMycardRoute
  '/_layout/pedidos-lojinha': typeof LayoutPedidosLojinhaRoute
  '/_layout/pedidos-sapatinho-veloz': typeof LayoutPedidosSapatinhoVelozRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/cards/add': typeof LayoutCardsAddRoute
  '/_layout/cards/associate': typeof LayoutCardsAssociateRoute
  '/_layout/cards/balance': typeof LayoutCardsBalanceRoute
  '/_layout/cards/create': typeof LayoutCardsCreateRoute
  '/_layout/cards/debit': typeof LayoutCardsDebitRoute
  '/_layout/historico/lanchonete': typeof LayoutHistoricoLanchoneteRoute
  '/_layout/historico/lojinha': typeof LayoutHistoricoLojinhaRoute
  '/_layout/historico/sapatinho': typeof LayoutHistoricoSapatinhoRoute
  '/_layout/lanchonete/select': typeof LayoutLanchoneteSelectRoute
  '/_layout/lojinha/select': typeof LayoutLojinhaSelectRoute
  '/_layout/sapatinho-veloz/sales': typeof LayoutSapatinhoVelozSalesRoute
  '/_layout/sapatinho-veloz/select': typeof LayoutSapatinhoVelozSelectRoute
  '/_layout/vendas/lanchonete': typeof LayoutVendasLanchoneteRoute
  '/_layout/vendas/lojinha': typeof LayoutVendasLojinhaRoute
  '/_layout/cards/': typeof LayoutCardsIndexRoute
  '/_layout/lanchonete/': typeof LayoutLanchoneteIndexRoute
  '/_layout/lojinha/': typeof LayoutLojinhaIndexRoute
  '/_layout/sapatinho-veloz/': typeof LayoutSapatinhoVelozIndexRoute
  '/_layout/lanchonete/products/create': typeof LayoutLanchoneteProductsCreateRoute
  '/_layout/lojinha/products/create': typeof LayoutLojinhaProductsCreateRoute
  '/_layout/sapatinho-veloz/products/create': typeof LayoutSapatinhoVelozProductsCreateRoute
  '/_layout/lanchonete/products/': typeof LayoutLanchoneteProductsIndexRoute
  '/_layout/lojinha/products/': typeof LayoutLojinhaProductsIndexRoute
  '/_layout/sapatinho-veloz/products/': typeof LayoutSapatinhoVelozProductsIndexRoute
  '/_layout/lanchonete/products/$id/edit': typeof LayoutLanchoneteProductsIdEditRoute
  '/_layout/lojinha/products/$id/edit': typeof LayoutLojinhaProductsIdEditRoute
  '/_layout/sapatinho-veloz/products/$id/edit': typeof LayoutSapatinhoVelozProductsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/admin'
    | '/mycard'
    | '/pedidos-lojinha'
    | '/pedidos-sapatinho-veloz'
    | '/'
    | '/cards/add'
    | '/cards/associate'
    | '/cards/balance'
    | '/cards/create'
    | '/cards/debit'
    | '/historico/lanchonete'
    | '/historico/lojinha'
    | '/historico/sapatinho'
    | '/lanchonete/select'
    | '/lojinha/select'
    | '/sapatinho-veloz/sales'
    | '/sapatinho-veloz/select'
    | '/vendas/lanchonete'
    | '/vendas/lojinha'
    | '/cards'
    | '/lanchonete'
    | '/lojinha'
    | '/sapatinho-veloz'
    | '/lanchonete/products/create'
    | '/lojinha/products/create'
    | '/sapatinho-veloz/products/create'
    | '/lanchonete/products'
    | '/lojinha/products'
    | '/sapatinho-veloz/products'
    | '/lanchonete/products/$id/edit'
    | '/lojinha/products/$id/edit'
    | '/sapatinho-veloz/products/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/admin'
    | '/mycard'
    | '/pedidos-lojinha'
    | '/pedidos-sapatinho-veloz'
    | '/'
    | '/cards/add'
    | '/cards/associate'
    | '/cards/balance'
    | '/cards/create'
    | '/cards/debit'
    | '/historico/lanchonete'
    | '/historico/lojinha'
    | '/historico/sapatinho'
    | '/lanchonete/select'
    | '/lojinha/select'
    | '/sapatinho-veloz/sales'
    | '/sapatinho-veloz/select'
    | '/vendas/lanchonete'
    | '/vendas/lojinha'
    | '/cards'
    | '/lanchonete'
    | '/lojinha'
    | '/sapatinho-veloz'
    | '/lanchonete/products/create'
    | '/lojinha/products/create'
    | '/sapatinho-veloz/products/create'
    | '/lanchonete/products'
    | '/lojinha/products'
    | '/sapatinho-veloz/products'
    | '/lanchonete/products/$id/edit'
    | '/lojinha/products/$id/edit'
    | '/sapatinho-veloz/products/$id/edit'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/_layout/admin'
    | '/_layout/mycard'
    | '/_layout/pedidos-lojinha'
    | '/_layout/pedidos-sapatinho-veloz'
    | '/_layout/'
    | '/_layout/cards/add'
    | '/_layout/cards/associate'
    | '/_layout/cards/balance'
    | '/_layout/cards/create'
    | '/_layout/cards/debit'
    | '/_layout/historico/lanchonete'
    | '/_layout/historico/lojinha'
    | '/_layout/historico/sapatinho'
    | '/_layout/lanchonete/select'
    | '/_layout/lojinha/select'
    | '/_layout/sapatinho-veloz/sales'
    | '/_layout/sapatinho-veloz/select'
    | '/_layout/vendas/lanchonete'
    | '/_layout/vendas/lojinha'
    | '/_layout/cards/'
    | '/_layout/lanchonete/'
    | '/_layout/lojinha/'
    | '/_layout/sapatinho-veloz/'
    | '/_layout/lanchonete/products/create'
    | '/_layout/lojinha/products/create'
    | '/_layout/sapatinho-veloz/products/create'
    | '/_layout/lanchonete/products/'
    | '/_layout/lojinha/products/'
    | '/_layout/sapatinho-veloz/products/'
    | '/_layout/lanchonete/products/$id/edit'
    | '/_layout/lojinha/products/$id/edit'
    | '/_layout/sapatinho-veloz/products/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/pedidos-sapatinho-veloz': {
      id: '/_layout/pedidos-sapatinho-veloz'
      path: '/pedidos-sapatinho-veloz'
      fullPath: '/pedidos-sapatinho-veloz'
      preLoaderRoute: typeof LayoutPedidosSapatinhoVelozRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/pedidos-lojinha': {
      id: '/_layout/pedidos-lojinha'
      path: '/pedidos-lojinha'
      fullPath: '/pedidos-lojinha'
      preLoaderRoute: typeof LayoutPedidosLojinhaRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/mycard': {
      id: '/_layout/mycard'
      path: '/mycard'
      fullPath: '/mycard'
      preLoaderRoute: typeof LayoutMycardRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/sapatinho-veloz/': {
      id: '/_layout/sapatinho-veloz/'
      path: '/sapatinho-veloz'
      fullPath: '/sapatinho-veloz'
      preLoaderRoute: typeof LayoutSapatinhoVelozIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/lojinha/': {
      id: '/_layout/lojinha/'
      path: '/lojinha'
      fullPath: '/lojinha'
      preLoaderRoute: typeof LayoutLojinhaIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/lanchonete/': {
      id: '/_layout/lanchonete/'
      path: '/lanchonete'
      fullPath: '/lanchonete'
      preLoaderRoute: typeof LayoutLanchoneteIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/cards/': {
      id: '/_layout/cards/'
      path: '/cards'
      fullPath: '/cards'
      preLoaderRoute: typeof LayoutCardsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/vendas/lojinha': {
      id: '/_layout/vendas/lojinha'
      path: '/vendas/lojinha'
      fullPath: '/vendas/lojinha'
      preLoaderRoute: typeof LayoutVendasLojinhaRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/vendas/lanchonete': {
      id: '/_layout/vendas/lanchonete'
      path: '/vendas/lanchonete'
      fullPath: '/vendas/lanchonete'
      preLoaderRoute: typeof LayoutVendasLanchoneteRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/sapatinho-veloz/select': {
      id: '/_layout/sapatinho-veloz/select'
      path: '/sapatinho-veloz/select'
      fullPath: '/sapatinho-veloz/select'
      preLoaderRoute: typeof LayoutSapatinhoVelozSelectRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/sapatinho-veloz/sales': {
      id: '/_layout/sapatinho-veloz/sales'
      path: '/sapatinho-veloz/sales'
      fullPath: '/sapatinho-veloz/sales'
      preLoaderRoute: typeof LayoutSapatinhoVelozSalesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/lojinha/select': {
      id: '/_layout/lojinha/select'
      path: '/lojinha/select'
      fullPath: '/lojinha/select'
      preLoaderRoute: typeof LayoutLojinhaSelectRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/lanchonete/select': {
      id: '/_layout/lanchonete/select'
      path: '/lanchonete/select'
      fullPath: '/lanchonete/select'
      preLoaderRoute: typeof LayoutLanchoneteSelectRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/historico/sapatinho': {
      id: '/_layout/historico/sapatinho'
      path: '/historico/sapatinho'
      fullPath: '/historico/sapatinho'
      preLoaderRoute: typeof LayoutHistoricoSapatinhoRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/historico/lojinha': {
      id: '/_layout/historico/lojinha'
      path: '/historico/lojinha'
      fullPath: '/historico/lojinha'
      preLoaderRoute: typeof LayoutHistoricoLojinhaRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/historico/lanchonete': {
      id: '/_layout/historico/lanchonete'
      path: '/historico/lanchonete'
      fullPath: '/historico/lanchonete'
      preLoaderRoute: typeof LayoutHistoricoLanchoneteRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/cards/debit': {
      id: '/_layout/cards/debit'
      path: '/cards/debit'
      fullPath: '/cards/debit'
      preLoaderRoute: typeof LayoutCardsDebitRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/cards/create': {
      id: '/_layout/cards/create'
      path: '/cards/create'
      fullPath: '/cards/create'
      preLoaderRoute: typeof LayoutCardsCreateRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/cards/balance': {
      id: '/_layout/cards/balance'
      path: '/cards/balance'
      fullPath: '/cards/balance'
      preLoaderRoute: typeof LayoutCardsBalanceRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/cards/associate': {
      id: '/_layout/cards/associate'
      path: '/cards/associate'
      fullPath: '/cards/associate'
      preLoaderRoute: typeof LayoutCardsAssociateRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/cards/add': {
      id: '/_layout/cards/add'
      path: '/cards/add'
      fullPath: '/cards/add'
      preLoaderRoute: typeof LayoutCardsAddRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/sapatinho-veloz/products/': {
      id: '/_layout/sapatinho-veloz/products/'
      path: '/sapatinho-veloz/products'
      fullPath: '/sapatinho-veloz/products'
      preLoaderRoute: typeof LayoutSapatinhoVelozProductsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/lojinha/products/': {
      id: '/_layout/lojinha/products/'
      path: '/lojinha/products'
      fullPath: '/lojinha/products'
      preLoaderRoute: typeof LayoutLojinhaProductsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/lanchonete/products/': {
      id: '/_layout/lanchonete/products/'
      path: '/lanchonete/products'
      fullPath: '/lanchonete/products'
      preLoaderRoute: typeof LayoutLanchoneteProductsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/sapatinho-veloz/products/create': {
      id: '/_layout/sapatinho-veloz/products/create'
      path: '/sapatinho-veloz/products/create'
      fullPath: '/sapatinho-veloz/products/create'
      preLoaderRoute: typeof LayoutSapatinhoVelozProductsCreateRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/lojinha/products/create': {
      id: '/_layout/lojinha/products/create'
      path: '/lojinha/products/create'
      fullPath: '/lojinha/products/create'
      preLoaderRoute: typeof LayoutLojinhaProductsCreateRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/lanchonete/products/create': {
      id: '/_layout/lanchonete/products/create'
      path: '/lanchonete/products/create'
      fullPath: '/lanchonete/products/create'
      preLoaderRoute: typeof LayoutLanchoneteProductsCreateRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/sapatinho-veloz/products/$id/edit': {
      id: '/_layout/sapatinho-veloz/products/$id/edit'
      path: '/sapatinho-veloz/products/$id/edit'
      fullPath: '/sapatinho-veloz/products/$id/edit'
      preLoaderRoute: typeof LayoutSapatinhoVelozProductsIdEditRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/lojinha/products/$id/edit': {
      id: '/_layout/lojinha/products/$id/edit'
      path: '/lojinha/products/$id/edit'
      fullPath: '/lojinha/products/$id/edit'
      preLoaderRoute: typeof LayoutLojinhaProductsIdEditRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/lanchonete/products/$id/edit': {
      id: '/_layout/lanchonete/products/$id/edit'
      path: '/lanchonete/products/$id/edit'
      fullPath: '/lanchonete/products/$id/edit'
      preLoaderRoute: typeof LayoutLanchoneteProductsIdEditRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutMycardRoute: typeof LayoutMycardRoute
  LayoutPedidosLojinhaRoute: typeof LayoutPedidosLojinhaRoute
  LayoutPedidosSapatinhoVelozRoute: typeof LayoutPedidosSapatinhoVelozRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutCardsAddRoute: typeof LayoutCardsAddRoute
  LayoutCardsAssociateRoute: typeof LayoutCardsAssociateRoute
  LayoutCardsBalanceRoute: typeof LayoutCardsBalanceRoute
  LayoutCardsCreateRoute: typeof LayoutCardsCreateRoute
  LayoutCardsDebitRoute: typeof LayoutCardsDebitRoute
  LayoutHistoricoLanchoneteRoute: typeof LayoutHistoricoLanchoneteRoute
  LayoutHistoricoLojinhaRoute: typeof LayoutHistoricoLojinhaRoute
  LayoutHistoricoSapatinhoRoute: typeof LayoutHistoricoSapatinhoRoute
  LayoutLanchoneteSelectRoute: typeof LayoutLanchoneteSelectRoute
  LayoutLojinhaSelectRoute: typeof LayoutLojinhaSelectRoute
  LayoutSapatinhoVelozSalesRoute: typeof LayoutSapatinhoVelozSalesRoute
  LayoutSapatinhoVelozSelectRoute: typeof LayoutSapatinhoVelozSelectRoute
  LayoutVendasLanchoneteRoute: typeof LayoutVendasLanchoneteRoute
  LayoutVendasLojinhaRoute: typeof LayoutVendasLojinhaRoute
  LayoutCardsIndexRoute: typeof LayoutCardsIndexRoute
  LayoutLanchoneteIndexRoute: typeof LayoutLanchoneteIndexRoute
  LayoutLojinhaIndexRoute: typeof LayoutLojinhaIndexRoute
  LayoutSapatinhoVelozIndexRoute: typeof LayoutSapatinhoVelozIndexRoute
  LayoutLanchoneteProductsCreateRoute: typeof LayoutLanchoneteProductsCreateRoute
  LayoutLojinhaProductsCreateRoute: typeof LayoutLojinhaProductsCreateRoute
  LayoutSapatinhoVelozProductsCreateRoute: typeof LayoutSapatinhoVelozProductsCreateRoute
  LayoutLanchoneteProductsIndexRoute: typeof LayoutLanchoneteProductsIndexRoute
  LayoutLojinhaProductsIndexRoute: typeof LayoutLojinhaProductsIndexRoute
  LayoutSapatinhoVelozProductsIndexRoute: typeof LayoutSapatinhoVelozProductsIndexRoute
  LayoutLanchoneteProductsIdEditRoute: typeof LayoutLanchoneteProductsIdEditRoute
  LayoutLojinhaProductsIdEditRoute: typeof LayoutLojinhaProductsIdEditRoute
  LayoutSapatinhoVelozProductsIdEditRoute: typeof LayoutSapatinhoVelozProductsIdEditRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutMycardRoute: LayoutMycardRoute,
  LayoutPedidosLojinhaRoute: LayoutPedidosLojinhaRoute,
  LayoutPedidosSapatinhoVelozRoute: LayoutPedidosSapatinhoVelozRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutCardsAddRoute: LayoutCardsAddRoute,
  LayoutCardsAssociateRoute: LayoutCardsAssociateRoute,
  LayoutCardsBalanceRoute: LayoutCardsBalanceRoute,
  LayoutCardsCreateRoute: LayoutCardsCreateRoute,
  LayoutCardsDebitRoute: LayoutCardsDebitRoute,
  LayoutHistoricoLanchoneteRoute: LayoutHistoricoLanchoneteRoute,
  LayoutHistoricoLojinhaRoute: LayoutHistoricoLojinhaRoute,
  LayoutHistoricoSapatinhoRoute: LayoutHistoricoSapatinhoRoute,
  LayoutLanchoneteSelectRoute: LayoutLanchoneteSelectRoute,
  LayoutLojinhaSelectRoute: LayoutLojinhaSelectRoute,
  LayoutSapatinhoVelozSalesRoute: LayoutSapatinhoVelozSalesRoute,
  LayoutSapatinhoVelozSelectRoute: LayoutSapatinhoVelozSelectRoute,
  LayoutVendasLanchoneteRoute: LayoutVendasLanchoneteRoute,
  LayoutVendasLojinhaRoute: LayoutVendasLojinhaRoute,
  LayoutCardsIndexRoute: LayoutCardsIndexRoute,
  LayoutLanchoneteIndexRoute: LayoutLanchoneteIndexRoute,
  LayoutLojinhaIndexRoute: LayoutLojinhaIndexRoute,
  LayoutSapatinhoVelozIndexRoute: LayoutSapatinhoVelozIndexRoute,
  LayoutLanchoneteProductsCreateRoute: LayoutLanchoneteProductsCreateRoute,
  LayoutLojinhaProductsCreateRoute: LayoutLojinhaProductsCreateRoute,
  LayoutSapatinhoVelozProductsCreateRoute:
    LayoutSapatinhoVelozProductsCreateRoute,
  LayoutLanchoneteProductsIndexRoute: LayoutLanchoneteProductsIndexRoute,
  LayoutLojinhaProductsIndexRoute: LayoutLojinhaProductsIndexRoute,
  LayoutSapatinhoVelozProductsIndexRoute:
    LayoutSapatinhoVelozProductsIndexRoute,
  LayoutLanchoneteProductsIdEditRoute: LayoutLanchoneteProductsIdEditRoute,
  LayoutLojinhaProductsIdEditRoute: LayoutLojinhaProductsIdEditRoute,
  LayoutSapatinhoVelozProductsIdEditRoute:
    LayoutSapatinhoVelozProductsIdEditRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
